import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";
import SideNav from './ui/dashboard/sidenav';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider options={{ key: 'css' }}>
      <div className = "flex-grow p-3 md:overflow-y-auto md:p12 bg-emerald-400">
        <SideNav/>
        <div className="m-3 mx-10 bg-yellow-300">
        {children}
        </div>
      </div>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
